### ISSUE TITLE
Format Request - Piraeus Bank, Greece

### ISSUE THREAD

**Issue by Firefly324** [leolabs/you-need-a-parser#1]
Hello! Would it be possible for you to add the parser for the Greek Piraeus Bank .csv format? I am attaching an example file, let me know if you need anything else. 

Thank you!

[Piraeus Bank - Greece Example File.zip](https://github.com/leolabs/you-need-a-parser/files/3242044/Piraeus.Bank.-.Greece.Example.File.zip)

**Comment by leolabs** [comment]
Could you tell me the original file name of the exported CSV file? YNAP primarily uses the file's name to determine which parser to use, only falling back on other methods when the file name isn't clear.

I'll try to implement it tomorrow if I get the time :)

**Comment by Firefly324** [comment]
The original file name is AccountStatement.csv 

However, I don't know if thats relevant but I don't export it directly from my bank, I request it via e-mail because the e-banking only provides .xlsx files.

Thank you very much!

**Comment by leolabs** [comment]
YNAP can also handle XLSX files. If it's easier to export your statements as XLSX, then I can implement that instead of the CSV parser. Could you provide an example file for the export?

**Comment by Firefly324** [comment]
Both are fine for me since I get my transactions via e-mail anyway. 

I am attaching also the .xlsx file in case you find it easier to implement.

[Account Transactions_20190601.xlsx](https://github.com/leolabs/you-need-a-parser/files/3243207/Account.Transactions_20190601.xlsx)

**Comment by leolabs** [comment]
I've implemented the parser for XLSX now in https://github.com/leolabs/you-need-a-parser/commit/0ef7ce32cbace3598f5d2689701b785808170dbd. You can try it out now if you'd like to :)

Please reload the browser once or twice to make sure the newest version of YNAP has been loaded.

**Comment by Firefly324** [comment]
Perfect! 

Thank you!

**Comment by Firefly324** [comment]
Hello! 

Recently Piraeus bank changed its export xlsx format and the parser is running into problems. The data now start in row 5 instead of row 7 and also the payee information is in column B instead of column D.  I have the new export file attached.

I would appreciate it if you could make the corrections in the parser whenever you get the time.

Thank you very much again, your script is very useful for me!

[Account Transactions_20200725.xlsx](https://github.com/leolabs/you-need-a-parser/files/4975776/Account.Transactions_20200725.xlsx)

**Comment by leolabs** [comment]
A fix should be online in a few minutes :)

**Comment by Firefly324** [comment]
Thank you!

**Comment by Firefly324** [comment]
Hello, Piraeus changed the format slightly again. The data starts in row 7 instead of row 5. 

Could you please take a look?

It seems like an easy fix, I could try to fix it myself but it seems I can't make a pull request.

Thank you again.

[Global Transaction List_20250725.xlsx](https://github.com/user-attachments/files/21432774/Global.Transaction.List_20250725.xlsx)
