### ISSUE TITLE
Bankernes EDB Central, gives empty return file 0bytes

### ISSUE THREAD

**Issue by duch11** [leolabs/you-need-a-parser#15]
**Describe the bug**
I just tried your terrific website, cudos! However I stumbled upon a bug while trying to upload and convert my file from "Bankernes EDB Central"

**To Reproduce**
1. Go to 'website'
2. Upload file from "Bankernes EDB Central" named "Posteringer"
3. Download resulting file
4. See that the file is of 0 bytes
5. Upload to YNAB, it gives an error.

**Expected behavior**
To have a properly converted CSV file

**Screenshots**
Extract from "Posteringer" file:
`16-09-2019;"DK-NOTA18438 STARMIDNIGHT KEBAB";-40,00; 14237,23;
16-09-2019;"DK-NOTA 4420 STØVLEN APS";-90,00; 14147,23;
`

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1903
 - Browser: Firefox 69.0.1

**Comment by leolabs** [comment]
Hey @duch11,

thanks for your bug report! Could you upload a full example of the file that you're trying to convert? If you do so, make sure to replace all personal information with placeholders.

It may be that the bank is not supported by YNAP yet, but normally, it should give you an error stating that.

**Comment by duch11** [comment]
Hi here you go, I think it should be supported as it works in Bank2YNAB
it's in a zip file due to github not supporting csv files :)
Hope this helps :)

[Posteringer.zip](https://github.com/leolabs/you-need-a-parser/files/3685820/Posteringer.zip)

**Comment by leolabs** [comment]
Thanks! I'll check it out and try to fix it today :)

**Comment by leolabs** [comment]
Hey @duch11,
I think I found the bug. I might have to write some more tests to make sure this doesn't happen again in the future :p 

Could you try converting the file again and see if it works for you now?

**Comment by leolabs** [comment]
I'm going to close this issue for now. If you still experience problems with the parsing, please feel free to re-open it :)
