### ISSUE TITLE
Sparbanken Tanum 2

### ISSUE THREAD

**Issue by trmd** [leolabs/you-need-a-parser#17]
My bank has changed export format during an upgade.

The files are named after the export date and time:
`Transaktioner_2019-10-12_14-57-29.csv`
translates as
`Transactions_YYYY-MM-DD_HH-MM-SS.csv`

The first line can be ignored (export period and creation date)
The second line can be ignored (header row)
Third line begins data, with these columns;:
skip,skip,skip,skip,skip,date,skip,skip,Payee,skip,Inflow and Outflow (represented by positive and negative values),skip

Hope that is enough! Thanks so much for this project and your work.

Sample file:

* Transaktioner Period 2019-10-01ñ2019-10-12 Skapad 2019-10-12 14:57 CEST
Radnummer,Clearingnummer,Kontonummer,Produkt,Valuta,Bokfˆringsdag,Transaktionsdag,Valutadag,Referens,Beskrivning,Belopp,Bokfˆrt saldo
1,83519,0036110559,"Privatkonto",SEK,2019-10-14,2019-10-12,2019-10-12,"ANTIKVARIAT NORD","Swish",-120.00,21834.16
2,83519,0036110559,"Privatkonto",SEK,2019-10-14,2019-10-12,2019-10-12,"Klaraspar","÷verfˆring",-11.00,21954.16
3,83519,0036110559,"Privatkonto",SEK,2019-10-11,2019-10-11,2019-10-11,"NOVARA MEDIA DON","Kortkˆp/uttag",-61.95,21965.16
4,83519,0036110559,"Privatkonto",SEK,2019-10-10,2019-10-10,2019-10-10,"HEMGLASS GOTEBOR","Kortkˆp/uttag",-119.00,22027.11
5,83519,0036110559,"Privatkonto",SEK,2019-10-10,2019-10-10,2019-10-10,"THE RED LION","Kortkˆp/uttag",-600.00,22146.11
6,83519,0036110559,"Privatkonto",SEK,2019-10-10,2019-10-10,2019-10-10,"SNABB SKO OCH NY","Kortkˆp/uttag",-160.00,22746.11
7,83519,0036110559,"Privatkonto",SEK,2019-10-10,2019-10-10,2019-10-10,"PARKERINGSBOLAGE","Kortkˆp/uttag",-319.00,22906.11
8,83519,0036110559,"Privatkonto",SEK,2019-10-10,2019-10-10,2019-10-11,"PARKERINGSBOLAGE","Kortkˆp/uttag",290.00,23225.11
9,83519,0036110559,"Privatkonto",SEK,2019-10-09,2019-10-09,2019-10-09,"TIER SE 10-54856","Kortkˆp/uttag",-20.00,22935.11

**Comment by leolabs** [comment]
Hey @trmd,
thanks for the update! Could you provide the sample file as an uploaded CSV file? GitHub seems to alter the formatting of the text you provided so I can't reliably work with it.

**Comment by trmd** [comment]
[Transaktioner_2019-10-12_14-57-29.csv.txt](https://github.com/leolabs/you-need-a-parser/files/3721636/Transaktioner_2019-10-12_14-57-29.csv.txt)

**Comment by leolabs** [comment]
I've implemented the new format (the old format is still supported). If it doesn't work for you, please feel free to re-open this issue :)
