### ISSUE TITLE
Format Request - Marcus by Goldman Sachs, United Kingdom

### ISSUE THREAD

**Issue by inversesandwich** [leolabs/you-need-a-parser#2]
Hi, I would like to request CSV import for Marcus in the UK. I have attached it to this issue.

Thanks in advance, and thanks for building such a snazzy web app!
[Marcus UK CSV.zip](https://github.com/leolabs/you-need-a-parser/files/3282585/Marcus.UK.CSV.zip)

**Comment by leolabs** [comment]
Hey @inversesandwich,
thanks for the request! I'll try to implement that tomorrow, by the looks of the csv file you supplied, it should be fairly easy to do :)

**Comment by inversesandwich** [comment]
Great!

Out of interest, do the parsers you add get contributed back to bank2ynab?

**Comment by leolabs** [comment]
For now, they don't, because the way YNAP's parsers work is a bit more complex than what bank2ynab's configuration allows. This is why YNAP can make use of bank2ynab but not the other way around.

**Comment by leolabs** [comment]
Sorry for the delay. The new parser should be online in a few minutes :)

**Comment by inversesandwich** [comment]
Hi Leo, apologies for bumping this issue.

It seems the parser isn't working, it just spits out the same file I upload. I've tested this with the original file I attached as well as a fresh one with new transactions.

Thanks for your help so far :)

**Comment by leolabs** [comment]
Oh, that's weird. Could you post the input and output files so I can check what's going on there? Please make sure to remove all personal information, as always.

**Comment by inversesandwich** [comment]
Here's the input and output files. The file ending in (1) is the output.
[Marcus Transactions NEW.zip](https://github.com/leolabs/you-need-a-parser/files/3316016/Marcus.Transactions.NEW.zip)

**Comment by leolabs** [comment]
Thanks! I have an idea what it could be. Could you tell me which browser and OS you're using? It seems like YNAP doesn't receive the dropped file at all, and the browser just opens/downloads the CSV you drop into the window.

**Comment by inversesandwich** [comment]
Ah! That might make sense. I'm using Firefox 67.0.4 on MacOS Mojave (10.14.5)

**Comment by leolabs** [comment]
Unfortunately, I don't have access to a computer until Tuesday, but I tested it all in Chrome. Could you check if it works there?

**Comment by inversesandwich** [comment]
I don't use Chrome but I tried in Safari and everything works as expected and imports into YNAB fine. Firefox was just showing a blank page after drag and dropping.

**Comment by leolabs** [comment]
Firefox is now supported as well.
