### ISSUE TITLE
Format Request - 1822direkt Frankfurter Sparkasse

### ISSUE THREAD

**Issue by joerncodes** [leolabs/you-need-a-parser#267]
Hey there, it would be awesome if you could provide a way to convert 1822direkt (Frankfurter Sparkasse) CSV files to YNAB.
I've attached a sample.
Thank you for your hard work!

[umsaetze-12345678-25.03.2020_11_45.csv.zip](https://github.com/leolabs/you-need-a-parser/files/4380825/umsaetze-12345678-25.03.2020_11_45.csv.zip)

**Comment by leolabs** [comment]
Thanks for your request! I'll get to it this afternoon :)

**Comment by joerncodes** [comment]
🙌

**Comment by leolabs** [comment]
I'm almost done. Do you know if it is possible to export statements for more than one account in one single file? I'm asking because of the first "Kontonummer" field. If that was the case, I would split the file into multiple output files, one for each account.

**Comment by joerncodes** [comment]
I just checked in the online banking software, and it doesn't seem possible. Each account produces a seperate csv file, in which the "Kontonummer" field is the same one for every row.

**Comment by leolabs** [comment]
The changes are currently building and should be online in a few minutes. Please check if it works for you. Feel free to re-open this ticket, should there be any problems :)

**Comment by joerncodes** [comment]
Hi!
Unfortunately, I get the message that no parser could be found.
The console gives me the following error:

`The file umsaetze-12345678-25.03.2020_14_54.csv was matched by <empty string>`

**Comment by leolabs** [comment]
Oh, I see. I deployed the site wrong. The correct version should be up in a few minutes. To check if you're using the newest version, please go to the [Supported Formats](https://ynap.leolabs.org/supported-formats/) page and look for 1822direkt :)

**Comment by joerncodes** [comment]
Works like a charm now. Thank you!

**Comment by leolabs** [comment]
Awesome! You're welcome :)
