### ISSUE TITLE
Format Request - Aqua, United Kingdom

### ISSUE THREAD

**Issue by inversesandwich** [leolabs/you-need-a-parser#3]
Hi, I've got another format that I'd like to be added to YNAP.
Insitiution: Aqua
Type: Credit card
Website: https://www.aquacard.co.uk/

[transactions.csv.zip](https://github.com/leolabs/you-need-a-parser/files/3318533/transactions.csv.zip)

Thanks!

**Comment by inversesandwich** [comment]
Awesome!

**Comment by leolabs** [comment]
It might take a few minutes for it to be deployed, I'll notify you when it's live.

**Comment by leolabs** [comment]
It's live! Could you try it out and give some feedback on whether it works for you?

**Comment by inversesandwich** [comment]
Converts fine but the inflow and outflow need swapping

**Comment by leolabs** [comment]
Thanks for that, I somehow overlooked it. The changes are deploying, you can see the current status [here](https://app.netlify.com/sites/you-need-a-parser/deploys/5d13eac68dc2790008672672).

**Comment by leolabs** [comment]
All changes are deployed now. The Aqua parser should now work as expected :)
