### ISSUE TITLE
errored: is not a valid date

### ISSUE THREAD

**Issue by bigblind** [leolabs/you-need-a-parser#362]
**Describe the bug**
When I drag in a file from ING Netherlands, I get an error sayin `<filename> errored: is not a valid date.`

**To Reproduce**
1. Go to https://ynap.leolabs.org/
2. Drag a file exported from an ING netherlands consumer checking account
(I'd prefer not to upload the file here, but if you want, I can email it to you)

**Expected behavior**
The file gets parsed

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 80

**Comment by leolabs** [comment]
Hey @bigblind,

thanks for reporting this error! To reproduce it, it would be nice to have the file you dragged into YNAP. When sending it to me, please make sure that you replace any personal information (especially IBANs) with placeholders (e.g. GB33BUKB20201555555555).

I'll try to fix the error as soon as I can :)

**Comment by bigblind** [comment]
Hi there. Here's the file. Ive turned all digits after NL30INGB into 0's in my own iban. All other details in there are from companies.
https://www.dropbox.com/s/jd5e8k02veokwvc/NL30INGB0000000000_25-06-2020_25-06-2020.csv?dl=0

The dropbox page says "CSV files are supported but something went wrong", which makes me think ING is sending malformed CSV files.

**Comment by leolabs** [comment]
Thanks for the file! I could find the error, but found another problem while trying to parse your file. Inflow and Outflow aren't specified by positive or negative numbers or by separate columns like in other banks, but by a separate column that specifies it ("Af" / "Bij"). Implementing that properly will take some time, but I'll tackle it this week :)

**Comment by leolabs** [comment]
Hey @bigblind,
I've just pushed a fix to your issue :)

Could you try it out and see if it works on your side? When you open the web app, you may get a prompt to reload after a few seconds so the new version can be installed.

**Comment by bigblind** [comment]
Yes that works now, thx!

**Comment by leolabs** [comment]
Awesome! Glad it works :)
