### ISSUE TITLE
N26: No parser is available for this file.

### ISSUE THREAD

**Issue by SheetMetalConnect** [leolabs/you-need-a-parser#478]
**Describe the bug**
N26 parsing recently stopped working, while it was functioning normally a couple of weeks ago. 

**To Reproduce**
1. Go to N26 and download CSV statement (current UI settings: English)
2. Upload to parser 

**Expected behavior**
I used this method for months in 2021, but it recently seemed to have stopped working.
Other converters (https://aniav.github.io/ynab-csv/) don't seem to have any difficulties with the file itself. It appears that the mapping or notation has changed.

**Sample**
Added a sample CSV here:
[n26-csv-transactions-sample.csv](https://github.com/leolabs/you-need-a-parser/files/7884176/n26-csv-transactions-sample.csv)

Thanks for this amazing parser!

**Comment by leolabs** [comment]
Thanks, it seems that N26 has removed a few columns from their exports which was the reason for YNAP not recognizing the file. I've improved the detection so it now works with the new format again. Let me know if this works for you :)
