### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by motin** [leolabs/you-need-a-parser#5]
`ynap-parsers` seems to be licensed under MIT. Is it fair to assume that all code in this repository is licensed under MIT?
A LICENSE file at the root repo level would be helpful :)

**Comment by leolabs** [comment]
Hey @motin,
thanks for the heads-up! I've added the GNU General Public License v3.0 to this project.

**Comment by motin** [comment]
Oh that's a bummer. I was just going to start using the package. Would you consider a more permissive license?
Btw, you have `ynap-parsers` still licensed under MIT according to https://github.com/leolabs/you-need-a-parser/blob/d87940841165484f1f93c7baf09bd115c6774abe/packages/ynap-parsers/package.json#L7.

**Comment by leolabs** [comment]
Oh, thanks! I overlooked that.

What would you need the more permissive MIT license for? Is there a part of GPL that prevents you from using this repo? :)

**Comment by motin** [comment]
> What would you need the more permissive MIT license for? Is there a part of GPL that prevents you from using this repo? :)

Yeah. Can't use GPL-licensed libraries/code for anything that will be released under a non-compatible license, so it is only useful for projects that are also GPL-licensed.

If you license under a more permissive license (ISC, MIT, BSD, MPL-2 etc), this will not be an issue. 

Note: bank2ynab is licensed under MIT, as is https://github.com/aniav/ynab-csv

**Comment by leolabs** [comment]
Alright, I've changed the license to MIT for the repo and all packages.

**Comment by motin** [comment]
> Alright, I've changed the license to MIT for the repo and all packages.

Great, thanks!
