### ISSUE TITLE
You need a praser broken ?

### ISSUE THREAD

**Issue by Juliendrinkscoffee** [leolabs/you-need-a-parser#653]
Good morning
I have tried to use your app since a couple of days without success
Is it me or there are some issues with You Need a Praser ?

many thanks for your work

Julien

**Comment by Juliendrinkscoffee** [comment]
Hello Leo,

I find a solution to my issue :
I was using your website with Brave browser ( shield down ) without
success
I have tried with Firefox , and it works
probably a question of blocking cookies or popup windows

thank you and sorry for the fuss

Julien

**Comment by leolabs** [comment]
No worries, I'm glad you found a solution!
